### ISSUE TITLE
A Standalone App

### ISSUE THREAD

**Issue by unsuitable001** [unsuitable001/BitViz#5]
Make a Standalone App. Using Electron/NW.js

**Comment by newvertex** [comment]
@unsuitable001 Hello, may I work on develop desktop App with Electron.js ?

**Comment by unsuitable001** [comment]
Go ahead @newvertex !!

**Comment by newvertex** [comment]
@unsuitable001 I've sent a PR to support desktop app,   
you can use `yarn build` to generate installer for current os or `yarn build:all` to generate installer for linux, windows and mac,  
I've made some changes to your main code because of some confilict, like use modal instead of prompt because it's not available in electron and ... but main major part of work flow and your main code is untouch and clear, feel free to comment or ask anything. ;-)

**Comment by unsuitable001** [comment]
Excellent work @newvertex . I'll test it then merge it.
